src/components/pages/MediationPage.js
src/components/pages/OfferPage.js
src/selectors/currentMediation.js
src/utils/routes.js

@Ledoux si tu es chaud pour review ça et brancher le backend, derrière je reprends la main !

Add mediations

---

src/components/layout/FormField.js
src/components/layout/FormSiret.js
src/components/pages/OffererPage.js

@augnustin @annemarie35 
j'avance un peu en rebasant et remergeant tout... comme ca je pourrai finir un peu ce plugin d'api compliqué ce week-end pour vous laisser ensuite le plaisir de faire du frontend à balle de blindax

Create or update venues

---

src/components/OfferersList.js
src/components/VenueItem.js
src/components/VenuesList.js
src/components/layout/FormSirene.js
src/components/pages/OffererPage.js
src/components/pages/VenuePage.js
src/selectors/currentOfferer.js
src/selectors/currentVenue.js
src/selectors/offerers.js
src/utils/routes.js

il manque encore
- intégrer le design de Ion
- les champs siren et siret non modifiable en patch
- l'autosizer à remettre en place dans venuesList (ou pas), en tout cas y'a une pass CSS
- vérifier après création d'une nouvelle venue, que c'est disponible dans state.venues et affiché dans offerer page
- tester côté api (notamment passer un zip code à l'api et faire la transfo en department_code côté back ?)

Offerer page with venues

---

src/components/hocs/withSign.js
src/components/layout/PageWrapper.js
src/components/pages/OffererPage.js
src/components/pages/SignupPage.js
src/components/pages/VenuePage.js
src/reducers/blockers.js
src/reducers/index.js
src/styles/global/page.scss

@augnustin 
bon en fait je l'ai fait maintenant l'ajout des listeners sur les location page change,
qui permet de faire qu'on peut enlever la notification selon nos conditions...
C'est un peu lourd (mais en même temps ca sera le code que l'on souhaitera aussi pour bloquer les chgmts de page quand l'utilisateur clique sur 'retour' alors que son formulaire est deja un peu rempli), donc ptet qu'à un moment on pourra refactorer ce truc

added blockers reducers to add notification close hook

---

src/components/OccurenceForm.js
src/components/OccurenceItem.js
src/components/OccurenceManager.js
src/components/pages/OfferPage.js
src/selectors/eventOccurenceForm.js
src/selectors/occasions.js
src/selectors/selectedOffererId.js
src/selectors/selectedVenueId.js
src/selectors/selectedVenues.js
src/selectors/types.js

@annemarie35 
la PR qui permet de desambiguer un peu l'offererId et la venueId choisi dans l'OfferPage

Fix type option

---

src/components/OccurenceForm.js
src/components/OccurenceItem.js
src/components/OccurenceManager.js
src/components/layout/FormDate.js
src/components/layout/FormField.js
src/components/pages/OfferPage.js
src/selectors/eventOccurenceForm.js
src/styles/components/OccurenceForm.scss
src/styles/components/index.scss
src/styles/components/layout/Modal.scss

Occurence form

---

src/App.js
src/components/OccurenceForm.js
src/components/OccurenceItem.js
src/components/OccurenceManager.js
src/components/layout/FormDate.js
src/components/layout/FormInput.js
src/components/pages/MediationPage.js
src/components/pages/OfferPage.js
src/styles/components/layout/Modal.scss
src/styles/global/layout.scss

Ca fonctionne, excepté les prix et le nombre de places qui ne sont pas des champs de eventOccurence, donc je ne vois pas trop comment il faut les gérer.

Event occurences

---

package.json
public/icons/ico-close-r.svg
src/components/OccurenceForm.js
src/components/OccurenceItem.js
src/components/OccurenceManager.js
src/components/layout/FormDate.js
src/styles/components/OccurenceForm.scss
src/styles/components/layout/FormDate.scss
src/styles/components/layout/index.scss
src/styles/vendors/index.scss
src/styles/vendors/react-virtualized.scss
src/utils/install.js
yarn.lock

Ca y est j'ai changé `react-dates` pour `react-datepicker` et c'est beaucoup (beaucoup) mieux ! :smile: 
J'ai fait une passe sur le design du formulaire, et me suis permis 2/3 libertés. A valider par @IonLzr bien-sûr.
Comme il est très compliqué (pour ne pas dire impossible) de faire un tableau, avec une hauteur maximale, dans une modale (ça complique), et deux lignes fixes (le header et le formulaire), il m'a semblé plus simple de:
- mettre le formulaire en haut
- répéter la ligne des headers sur la dernière ligne si plus de 12 événements (sur mon écran, c'est le nombre max qu'on peut voir en simultané, on peut augmenter au besoin).
C'est beaucoup plus simple de créer un event, car directement accessible, et c'est moins gênant de ne pas avoir les intitulés de colonnes quand c'est 100 …

New datepicker

---

public/icons/ico-sort-ascending.svg
public/icons/ico-sort-descending.svg
src/components/layout/InfiniteScroller.js
src/components/layout/PageWrapper.js
src/components/pages/OccasionsPage.js
src/selectors/createOccasions.js
src/styles/components/OccasionItem.scss
src/styles/components/pages/OffersPage.scss
src/styles/global/layout.scss
src/utils/string.js

Ca fonctionne.
Après ça reste un joyeux bordel puisqu'on a 3 sources of truth différentes : le store, le path, et le state (dans le cas de la pagination). Donc on ne va clairement pas dans le sens de la simplification du code souhaitée.
Mais bon, on pourra y réfléchir dans un second temps.
Je n'ai pas encore traduit les libellés dans le search: `offererId=A9` au lieu de `structure=A9`. Pas sûr de cautionner la traduction perso.

Occasions filters

---

jest.config.js
jest.setup.js
package.json
scripts/jesttest.js
src/components/pages/tests/SigninPage.test.js
src/components/pages/tests/__snapshots__/SigninPage.test.js.snap
yarn.lock

Premier boostrap pour la mise en place de tests sur les selectors et un composant simple.

add first test and config files

---

testcafe/01_signup.js
testcafe/02_signin.js
testcafe/03_offerers.js
testcafe/04_offerer.js
testcafe/05_venue.js
testcafe/06_create_offer.js

pc reset-all-db
puis
yarn testcafe

Us #423 add new functionnal tests

---

src/App.js
src/components/OccurenceForm.js
src/components/layout/PageWrapper.js
src/components/pages/OccasionPage.js
src/components/pages/SigninPage.js
src/components/pages/SignupPage.js
src/components/pages/VenuePage.js
src/selectors/occasionPatch.js
src/selectors/occurence.js
src/selectors/offer.js
src/selectors/venue.js
src/styles/vendors/bulma-with-overrides.scss
src/utils/form.js

from https://github.com/betagouv/pass-culture-pro/pull/80/files

reused 384_is_national_rebased

---

package.json
src/Root.js
src/components/OfferItem.js
src/components/layout/Main.js
src/components/pages/OffersPage.js
src/reducers/index.js
src/sagas/index.js
src/utils/persist.js
src/utils/persistor.js
src/utils/store.js
yarn.lock

en ajoutant dans le saga data 
ce qu'il faut de ce qui a été fait ici
https://github.com/betagouv/pass-culture-pro/pull/59

added redux-persist and add the isNew feature

---

.circleci/config.yml
testcafe/06_offer.js
testcafe/07_mediation.js

Une fois cette PR mergée,
les tests marcheront!!!

circle ci api

---

src/components/pages/OfferPage.js

https://github.com/betagouv/pass-culture-browser/issues/439
besoin de https://github.com/betagouv/pass-culture-shared/pull/12
ion design:
rendu:

439 Display description length

---

package.json
src/components/layout/GeoInput.js
src/components/pages/OffersPage.js
src/components/pages/VenuePage.js
src/styles/components/layout/FormGeo.scss
src/styles/components/layout/index.scss
src/utils/persist.js

le FormGeo scss avait mysterieusement disparu...

polished form

---

src/components/pages/OfferPage.js

Du bug qu'on avait:
De la page Vos Offres, si on cliquait sur une offre pour aller vers sa page OfferPage,
les selecteurs Offerer et Structure ne se settaient pas automatiquement

fixed automatic redirect with venue param

---

src/components/pages/OfferPage.js

590 591 592 593 594 595 add offer fields

---

src/components/pages/OfferPage.js

fixed readonly for structure and venue

---

package.json
src/components/pages/OfferersPage.js
src/components/pages/OffersPage.js
src/utils/search.js
yarn.lock

a besoin de ça cote API: https://github.com/betagouv/pass-culture-api/pull/200
a besoin de ça cote shared: https://github.com/betagouv/pass-culture-shared/pull/39

readapted offers page with search

---

package.json
src/components/layout/BicInput.js
src/components/layout/IbanInput.js
src/components/pages/OffererPage.js
src/styles/global/form.scss
src/utils/form.js
testcafe/04_offerer.js
yarn.lock

Issue : https://github.com/betagouv/pass-culture-browser/issues/619

#619 Add basic fields for IBAN and BIC

---

src/selectors/types.js

en fait c'était pas done ça https://github.com/betagouv/pass-culture-browser/issues/545

fixed typesSelector

---

src/components/managers/EventOccurrencesAndStocksManager.js

https://github.com/betagouv/pass-culture-browser/issues/651

 #651 Hide add button

---

src/utils/pagination.js

comme cette PR (https://github.com/betagouv/pass-culture-api/pull/200) sur api est enfin mergée on peut.

readapted search to keywords

---

src/components/pages/AccountingPage.js
src/components/pages/OfferersPage.js
src/components/pages/OffersPage.js

fixed keywords in search

---

src/components/pages/OffererPage.js
testcafe/04_offerer.js

le tps qu'on est sur que ca marche avec des tests.

removed iban and bic temporairement

---

package.json
public/icons/picto-info.svg
src/components/layout/GeoInput.js
src/components/layout/Main.js
src/components/layout/SirenInput.js
src/components/pages/OffererPage.js
src/components/pages/SignupPage.js
src/components/pages/VenuePage.js
src/sagas/form.js
src/selectors/selectVenuePatchByVenueIdByOffererId.js
src/selectors/venue.js
src/styles/components/layout/GeoInput.scss
src/styles/global/index.scss
src/styles/global/tooltip.scss
src/styles/vendors/index.scss
yarn.lock

Comme on est un peu pressé pour faire que l'ux soit clair pour le test utilisateur mercredi...
j'ai un peu choisi rapidement la lib react-tooltip pour faire les tooltip dans la page Venue.
Je serai bien sur apres jeudi flexible à ce qu'on utilise une autre lib de tooltip si vous voulez!

Tooltip pro et Test avec les tooltips à faire dans VenuePage

---

src/components/layout/Header.js

Donc là par exemple,
j'ai deja fait un commit de clean du code du component Header.
Mais je trouvais ca trop long de faire une PR "clean Header" juste pour ce commit,
puis refaire une nouvelle PR pour mon commit "feature" redirect du bouton "VosOffres" ou dedans j'aurais cherry-pické le commit de la "PR clean Header" pour ensuite faire mon commit feature.
Du coup je trouvais ca plus handy de faire ca dans une seule PR...:p jveux bien qu'on me dise une meilleure solution pour que cela soit lisible quand meme pour les reviewers.

Le bouton "Vos Offres" doit toujours rediriger ves "Vos Offres" sans query (keywords, prefiltre lieu ou structure)

---

package.json
src/components/items/MediationItem.js
src/components/layout/UploadThumb.js
src/components/managers/MediationsManager.js
src/components/pages/MediationPage.js
testcafe/07_mediation.js
yarn.lock

https://octo.invisionapp.com/d/#/console/14441549/300306235/preview

Mediation Page: converger vers le design de in vision

---

package.json
src/components/items/EventOccurrenceAndStockItem/PriceQuantityForm.js
yarn.lock

Upgrade of shared is required : https://github.com/betagouv/pass-culture-shared/pull/52

#778 Allow decimal prices

---

testcafe/02_signin.js
testcafe/04_offerer.js
testcafe/05_venue.js

ce qui explique pk les tests passaient plus dans les deux dernières PR

Testcafe adaptation

---

package.json
src/components/pages/OffererPage.js

@arnoo @g4vroche 
important et c'est un EXPEDIT: là dans cette PR, les champs IBAN et BIC deviennent editable en mode modifie et on peut donc les changer. (mais donc sont en readonly sinon).
A voir si ca marche. Sinon on les cache tant que ca marche pas.

[BLOCKED] made iban and bic Offerer creatable et editable

---

package.json
src/components/pages/MediationPage.js
src/components/pages/OffererPage.js
src/components/pages/VenuePage.js
src/reducers/data.js
src/selectors/offerer.js
src/selectors/selectUserOffererByOffererIdAndUserIdAndRightsType.js
testcafe/04_offerer.js
yarn.lock

à merger au plus vite ce matin... pour faire que les biz devs puissent tranquillement remplir les offres pour PGW, ET que les acteurs culturels en prod puissent enfin remplir leur siren.
MAIS il faut que la MEP API jsute avant merge aussi ces deux PR
https://github.com/betagouv/pass-culture-api/pull/253
et https://github.com/betagouv/pass-culture-api/pull/274
...je sais c'est le bordel, mais encore une fois j'ai la sensation d'etre pris de court avec cette PGW qui demande des trucs tt de suite en dehors de la temporalité de notre kanban. faudrait que j'arrive à dire non en fait.

Emergency fixes

---

src/components/pages/OfferersPage.js
src/components/pages/offerers/PendingOffererItem.js
src/reducers/data.js
src/selectors/offerers.js
src/styles/components/pages/OfferersPage.scss
testcafe/01_signup.js

En attente des gros merges sur offerer pour écrire les tests fonctionnels sans quoi la suite va être pleine de conflits relous.
Rendu temporaire car pas de maquette pour ça pour le moment (ping @IonLzr ) :

#859 Show pending offerers in offerers page

---

package.json
src/components/pages/Offer/EventOccurrenceAndStockItem/Actions.jsx
src/components/pages/Offer/index.jsx
src/components/pages/Signin.jsx
testcafe/02_signin.js
testcafe/06_offer.js
yarn.lock

Requires shared upgrade: https://github.com/betagouv/pass-culture-shared/pull/70

pc-366 Submit signin form on key press enter

---

package.json
yarn.lock

needs https://github.com/betagouv/pass-culture-shared/pull/73

PC 1118 fix scroll

---

src/components/pages/Signup/SignupConfirmation.jsx
src/components/pages/Signup/SignupForm.jsx
src/styles/_variables.scss
src/styles/components/pages/SignInAndUpPage.scss
src/styles/vendors/bulma.scss

Retouches de CSS après revue avec Ion

(PC-51) Change css of signup confirmation page after graphical review

---

src/components/pages/Offerer/index.jsx
testcafe/04_offerer.js
testcafe/05_venue.js

Rend l'adresse facultative dans le formulaire de la page structures/nouveau rempli grâce à l'api sirene

1082 making address nullable

---

src/components/pages/Mediation/index.jsx
src/styles/components/pages/MediationPage.scss

Needs merge on https://github.com/betagouv/pass-culture-homepage/pull/1

PC-1032 Activate link to ressources

---

package.json
src/components/pages/Signup/SignupForm.jsx
src/styles/global/form.scss
yarn.lock

nécessaire d'avoir https://github.com/betagouv/pass-culture-shared/pull/81

[PC-1172] tooltip password

---

package.json
src/components/pages/Signup/SignupForm.jsx
src/styles/global/tooltip.scss
yarn.lock

pour fixer le indent dans le tooltip

1172 microfix style

---

src/components/layout/RawHeader.jsx
src/components/layout/tests/RawHeader.test.jsx
src/components/layout/tests/__snapshots__/RawHeader.test.jsx.snap
src/components/pages/Offerer/index.jsx
src/components/pages/Offerers/RawIndex.jsx
src/components/pages/Offerers/tests/__snapshots__/indexContent.test.jsx.snap
src/components/pages/Offerers/tests/indexContent.test.jsx

j'ai juste modifié vos structures en vos structures juridiques et votre structure en votre structure juridique

pc-1175 add jurique to label after PO review

---

src/styles/global/form.scss

(PC-1045) fixed bottom in last child columns in help of field body form

---

package.json
src/components/pages/Offer/EventOccurrenceAndStockItem/PriceQuantityForm.jsx
src/styles/components/layout/Modal.scss
src/styles/components/layout/index.scss
src/styles/components/managers/EventOccurrencesAndStocksManager.scss
yarn.lock

```
yarn install
```
pour avoir pass culture shared 0.0.100

(PC-134) made alert box designed like the modal behind

---

src/components/pages/Offer/index.jsx

Il y a aussi une partie API (cf. PR de Sofía)

[PC-1473] Add bookingEmail to offerForm

---

jest.setup.js
package.json
src/Root.jsx
src/components/pages/Offers/RawOffers.jsx
src/components/pages/Offers/index.jsx
src/components/pages/Offers/tests/RawOffers.test.jsx
src/components/pages/Offers/tests/index.test.jsx
src/utils/persistor.js
src/utils/store.js
yarn.lock

(Pc-1620) fix reset of page when click on venue offerer flag

---

src/components/pages/Offer/RawOffer.js
src/components/pages/Offer/tests/__snapshots__/RawOffer.spec.jsx.snap
src/styles/components/layout/Block.scss
src/styles/components/pages/OfferPage.scss

pour le margin sur le subtitle, 
j'aurais bien simplement rajouté la classe mb12
mais il a jamais voulu la prendre en compte comme ça:/

PC-152 graphic review, update spnapshots

---

src/components/layout/form/fields/DateField.jsx
src/components/layout/form/fields/tests/DateField.spec.jsx
src/components/layout/form/fields/tests/__snapshots__/DateField.spec.jsx.snap
src/components/layout/form/fields/tests/__snapshots__/TimeField.spec.jsx.snap
src/components/pages/Offer/StocksManager/StockItem/EventFields.jsx
src/components/pages/Offer/StocksManager/StockItem/StockItem.jsx
src/components/pages/Offer/StocksManager/StockItem/fillEndDatimeWhenUpdatingBeginningDatetime.jsx
src/components/pages/Offer/StocksManager/StockItem/tests/__snapshots__/EventFields.spec.jsx.snap
src/components/pages/Offer/StocksManager/StockItem/tests/__snapshots__/ProductFields.spec.jsx.snap
src/components/pages/Offer/StocksManager/StockItem/tests/fillEndDatimeWhenUpdatingBeginningDatetime.spec.js
src/components/pages/Offer/StocksManager/tests/StocksManager.spec.jsx

bugs 1 & 2 sur ce ticket
https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=2&modal=detail&selectedIssue=PC-1873

Pc 1873 autocomplete end date time

---

.circleci/config.yml
scripts/install_lib_ci_pro.sh

This reverts commit 758cf60e79dd83d657679ba377d6f00ca122f4b1.

Revert "(PC-2207) code review"

---

src/components/pages/Offers/Offers.jsx
src/components/pages/Offers/__specs__/__snapshots__/Offers.spec.jsx.snap

(PC-2243) : Offers page pagination + offers load after search

---

src/components/pages/Bookings/FilterByOffer/FilterByOfferContainer.js
src/components/pages/Bookings/FilterByOffer/__specs__/FilterByOfferContainer.spec.js
src/components/pages/Bookings/FilterByVenue/FilterByVenue.jsx
src/components/pages/Bookings/FilterByVenue/FilterByVenueContainer.js
src/components/pages/Bookings/FilterByVenue/__specs__/FilterByVenue.spec.jsx
src/components/pages/Bookings/FilterByVenue/__specs__/FilterByVenueContainer.spec.js
src/components/pages/Bookings/FilterByVenue/__specs__/__snapshots__/FilterByVenue.spec.jsx.snap
src/components/pages/Bookings/selectors/__specs__/selectIsUserAdmin.spec.js
src/components/pages/Bookings/selectors/selectIsUserAdmin.js

…pty for admin user and a notification warn them that they cannot downlaod the booking csv file

(PC-2105) : Remove access to booking csv file for admin user

---

src/components/pages/Offerers/Offerers.jsx
src/components/pages/Offerers/OfferersContainer.jsx
src/components/pages/Offerers/__specs__/OfferersContainer.spec.jsx
src/components/pages/Offerers/__specs__/__snapshots__/Offerers.spec.jsx.snap
src/components/pages/Offerers/utils/__specs__/userHasNoOffersInAPhysicalVenueYet.spec.jsx
src/components/pages/Offerers/utils/userHasNoOffersInAPhysicalVenueYet.jsx

(PC-2280) : Fix search query + scroller for offerers

---

src/selectors/__specs__/mockState.json

(PC-2288) : Rename instruments category

---

src/components/pages/Offer/StocksManager/StockItem/selectors/__specs__/selectFormInitialValuesByStockAndOfferIdAndOffererId.spec.js
src/components/pages/Offer/StocksManager/StockItem/selectors/selectFormInitialValuesByStockAndOfferIdAndOffererId.js

…ter the previous stock bokioking limit datetime

(PC-1353) : automatically set booking limit data time value

---

src/components/pages/Venue/VenueProvidersManager/VenueProviderItem/VenueProviderItem.jsx
src/components/pages/Venue/VenueProvidersManager/VenueProviderItem/__specs__/VenueProviderItem.spec.jsx
src/components/pages/Venue/VenueProvidersManager/VenueProviderItem/__specs__/__snapshots__/VenueProviderItem.spec.jsx.snap
src/components/pages/Venue/VenueProvidersManager/VenueProvidersManager.jsx
src/components/pages/Venue/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
src/components/pages/Venue/VenueProvidersManager/__specs__/__snapshots__/VenueProvidersManager.spec.jsx.snap
src/components/pages/Venue/VenueProvidersManager/form/SelectSourceField/__specs__/SelectSourceField.spec.js
src/components/pages/Venue/VenueProvidersManager/utils/__specs__/checkIfProviderShouldBeDisabled.spec.js
src/components/pages/Venue/VenueProvidersManager/utils/checkIfProviderShouldBeDisabled.js
src/styles/components/pages/Venue/VenueProvidersManager/VenueProviderItem/_VenueProviderItem.scss
src/styles/components/pages/Venue/VenueProvidersManager/VenueProvidersManager.scss
src/styles/components/pages/Venue/VenueProvidersManager/index.scss

(PC-2355) : Fix Allocine - le retour

---

src/components/pages/Offerers/OffererItem/OffererItem.jsx
src/components/pages/Offerers/OffererItem/__specs__/OffererItem.spec.jsx
src/components/pages/Offerers/OffererItem/__specs__/__snapshots__/OffererItem.spec.jsx.snap
src/components/pages/Venue/Venue.jsx
src/components/pages/Venue/__specs__/Venue.spec.jsx
src/components/pages/Venue/controls/CreateControl/CreateControl.jsx
src/components/pages/Venue/controls/CreateControl/__specs__/CreateControl.spec.jsx
src/components/pages/Venue/controls/CreateControl/__specs__/__snapshots__/CreateControl.spec.jsx.snap

- Retour PO = mise à jour des liens de création d'offre depuis la page de détail d'un lieu, il manquait la structure dans l'url

(PC-2591) : fix css

---

src/styles/components/pages/Offer/StocksManager/_StocksManager.scss
src/styles/variables/_guidelines.scss

Add styling on bookings count, bsr on rem - px, add color variable for black with transparency

(PC-2844): Graphic Review

---

config/webpack.config.dev.js

https://github.com/facebook/create-react-app/pull/7587
https://webpack.js.org/loaders/eslint-loader/#cache

(pC-3260) reduce time from eslint loader

---

src/components/pages/Bookings-v2/BookingsRecapTable/BookingsRecapTable.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/FilterByBookingPeriod.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/FilterByEventDate.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/FilterByOmniSearch.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/FilterByVenue.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/Filters.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/__specs__/FilterByBookingPeriod.spec.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/__specs__/FilterByEventDate.spec.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/__specs__/FilterByOmniSearch.spec.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/__specs__/FilterByVenue.spec.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/Filters/__specs__/Filters.spec.jsx
src/components/pages/Bookings-v2/BookingsRecapTable/utils/__specs__/filterBookingsRecap.spec.js
src/components/pages/Bookings-v2/BookingsRecapTable/utils/__specs__/formatAndOrderVenues.spec.js
src/components/pages/Bookings-v2/BookingsRecapTable/utils/filterBookingsRecap.js
src/components/pages/Bookings-v2/BookingsRecapTable/utils/formatAndOrderVenues.js
src/styles/components/pages/BookingsV2/BookingsRecapTable/Filters/_Filters.scss

+ refacto des filters (extraction dans des sous composants)

(PC-3300) : Add Filter by beneficiaries firstname, lastname & email

---

src/components/pages/Bookings/BookingsRecapTable/Table/Head/Head.jsx

Note: A ne pas merger pour l'instant, regression sur Firefox Mac

[PC-3855]: Add rule for activating sorting on enter pressing

---

.eslintrc
config/paths.js
config/webpack.config.dev.js
config/webpack.config.prod.js
src/index.jsx

Les import absolut fonctionnent mais j'ai un soucie de configuration pour eslint qui ne comprend pas les chemins:
```
./src/index.jsx
Line 6:   Unable to resolve path to module 'src/utils/init'     import/no-unresolved
Line 7:  Unable to resolve path to module 'src/Root'           import/no-unresolved
Line 8:  Unable to resolve path to module 'src/workers/cache'  import/no-unresolved
```

PC-4525 Configure absolute import

---

jest.config.js
package.json
src/components/layout/DownloadButton/__specs__/DownloadButtonContainer.spec.jsx
src/components/pages/Bookings/BookingsRecapTable/Table/__specs__/TableFrame.spec.jsx
src/components/pages/Profil/tests/Profil.spec.jsx
yarn.lock

Dans cette PR se situe quelques exemples de comment on récupère les éléments sur la page (par rôle, par texte, par texte du label associé) et de comment on déclenche des événements (fireEvent.click et fireEvent.change)
Aussi, il s'agit d'un changement de conception, puisqu'on ne regarde pas si le bouton a une propriété disabled mais on simule un click et on s'attend à ce que le dispatch ne parte pas.

(PC-4548): Add react testing library on pro

---

package.json
src/components/pages/Offers/__specs__/Offers.spec.jsx
src/store/reducers/bookingSummary/bookingSummary.js
src/store/reducers/data.js
src/store/reducers/errors.js
src/store/reducers/maintenanceReducer.js
src/store/reducers/modal.js
src/store/reducers/offers.js
src/store/testUtils.js
src/utils/testHelpers.js
yarn.lock

https://passculture.atlassian.net/browse/PC-4814

[PC-4814] pages.Offers.specs: migrate to react-testing-library

---

src/components/layout/form/fields/TextField.jsx
src/components/pages/Venue/fields/LocationFields/LocationFields.jsx

Le 3ème commit est une proposition vis à vis du destructuring ;). 
J'aimerais avoir vos avis dessus.

[PC-4318] Création de lieu : autoriser les coordonnées jusqu'à 5 décimales

---

src/components/layout/ActionsBar/ActionsBar.jsx
src/components/layout/ActionsBar/__specs__/ActionsBar.spec.jsx
src/components/layout/ActionsBar/index.js
src/components/layout/Main/Main.jsx
src/components/pages/Offers/ActionsBar/ActionsBar.jsx
src/components/pages/Offers/ActionsBar/__specs__/ActionsBar.spec.jsx
src/components/pages/Offers/ActionsBar/index.js
src/components/pages/Offers/OfferItem/OfferItem.jsx
src/components/pages/Offers/Offers.jsx
src/components/pages/Offers/OffersContainer.js
src/components/pages/Offers/__specs__/Offers.spec.jsx
src/store/reducers/actionsBar.js
src/store/reducers/index.js
src/store/reducers/offers.js
src/styles/components/layout/buttons/PrimaryButton/_PrimaryButton.scss
src/styles/components/pages/Offers/_ActionsBar.scss
src/styles/components/pages/Offers/index.scss
src/styles/global/_ActionsBar.scss
src/styles/global/_buttons.scss
src/styles/global/index.scss
src/utils/testHelpers.js

Afin d’alléger cette Pr, il serait bon de review / merger https://github.com/pass-culture/pass-culture-pro/pull/761 en amont. (migration des test vers RTL)

(PC-4284) Offers: add checkbox selection

---

src/components/layout/form/fields/SirenField/SirenField.jsx
src/components/pages/Offerer/OffererCreation/OffererCreationForm/OffererCreationForm.jsx
src/components/pages/Offerer/OffererCreation/decorators/__specs__/getSirenInformation.spec.js
src/components/pages/Offerer/OffererCreation/decorators/getSirenInformation.js

https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=16&projectKey=PC&modal=detail&selectedIssue=PC-3428

(PC-3428) : fix "autoentrepreneur" name

---

src/components/pages/Offers/OffersContainer.js
src/repository/pcapi/pcapi.js
src/repository/pcapi/pcapiClient.js
src/store/offers/thunks.js

request data vas automagiquement merger le retour d'activate / deactivate dans la store data.
Il nous faut utiliser le store offers.

(PC-4892): OffersContainer: Remove request data for activate / deactivate bulk offers

---

src/store/offers/thunks.js
src/store/reducers/data.js

Retrait de requestData pour les offres episode 12:
Il nous faut aussi mettre à jours les mediations...

(PC-4892): Fill data.mediations on loadOffers

---

src/components/pages/Offers/Offers.jsx
src/components/pages/Offers/__specs__/Offers.spec.jsx
src/components/pages/Offers/_constants.js
src/repository/pcapi/pcapi.js
src/styles/components/pages/Offers/_Offers.scss
src/utils/translate.js

Ajout du filtre par catégories pour les offres
todo: ajout des tests.

 (PC-4291): Offers : Add filter by type

---

src/components/pages/Offers/Offers.jsx

Offers: fix typo on TypeId variable

---

src/components/pages/Bookings/BookingsRecapTable/utils/generateBookingsCsvFile.js

Bookings recap page crashed in case of booking made by a user with no last name

(PC-5050) Fix bookings page display

---

src/components/pages/Offers/OfferItem/OfferItem.jsx
src/styles/components/pages/Offers/OfferItem/_OfferItem.scss

retour sur le ticket https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=31&projectKey=PC&modal=detail&selectedIssue=PC-4915
oublie de retirer les liens sur les stocks et de ne pas afficher les stocks si ceux ci ne sont pas des dates.

(PC-4915) : Remove stocks string and dates link

---

src/components/layout/Banner/Banner.jsx
src/components/layout/Banner/__specs__/Banner.spec.jsx
src/components/layout/Banner/index.js
src/components/pages/Offerer/OffererDetails/BankInformation/BankInformation.jsx
src/components/pages/Offerer/OffererDetails/BankInformation/__specs__/BankInformation.spec.jsx
src/components/pages/Reimbursements/Reimbursements.jsx
src/components/pages/Reimbursements/__specs__/Reimbursements.spec.jsx
src/components/pages/Venue/fields/BankInformationFields/ApplicationBanner.jsx
src/components/pages/Venue/fields/BankInformationFields/BankInformationFields.jsx
src/components/pages/Venue/fields/BankInformationFields/__specs__/ApplicationBanner.spec.jsx
src/components/pages/Venue/fields/BankInformationFields/__specs__/BankInformation.spec.jsx
src/styles/components/layout/Banner/_Banner.scss
src/styles/components/layout/Banner/index.scss
src/styles/components/layout/index.scss
src/styles/components/pages/Offerer/BankInformation/_BankInformation.scss

Link to ticket: https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=16&modal=detail&selectedIssue=PC-4946
Ajout d'un composant `<Banner />` qui sera réutilisable, et qui permet d'avoir des tests plus clairs également.

[PC-4946] Ajout de la mention "En savoir plus sur les remboursements"

---

src/components/pages/Offers/Offers.jsx

* change link design when no filters
* also reset offerer filter
* link wording

(PC-4287) : reinitialize filters fixes

---

src/components/pages/Offers/Offers.jsx
src/styles/components/pages/Offers/_Offers.scss

(PC-4571) : Offers: Reset filters button should be disabled when no filters active

---

package.json
yarn.lock

[quick win] remove la-sass-vy

---

src/components/pages/Offers/Offers.jsx
src/components/pages/Offers/StatusFiltersButton.jsx
src/components/pages/Offers/__specs__/Offers.spec.jsx
src/components/pages/Offers/_constants.js
src/styles/components/pages/Offers/_Offers.scss

Show status filters and select all offers checkbox to admins only if venue or offerer filter is applied

(PC-5070) Show status filters and select all offers checkbox to admins

---

src/styles/global/_forms.scss

[En voulant bien faire, on a fait remonter une erreur](https://github.com/pass-culture/pass-culture-pro/pull/855/files#diff-5ca79eb82daf524637913a1a44c3259ee28a261c74adba36acc0a0d4c50c4516R53).

(PC-5474) deleting of background on field select

---

config/webpack.config.js
package.json
src/index.jsx
yarn.lock

Investigations ici https://www.notion.so/Pro-Bundle-Analyze-074bbf0751b74b25bb2c1c1338834c33

(PC-5518): Filter loaded timezones

---

config/webpack.config.js
src/utils/timezone.js

See also pass-culture/pass-culture-api@d58134c08db2b57241ff50fe13791d3090ceafd1

(PC-5520) timezones: Handle more overseas départements

---

src/components/layout/inputs/TimeInput.jsx
src/components/pages/Styleguide/Styleguide.jsx
src/components/pages/Styleguide/StyleguideAgenda.jsx
src/components/pages/Styleguide/StyleguideElements/StyleguideInputTime.jsx
src/styles/components/layout/inputs/_TimeInput.scss
src/styles/components/layout/inputs/index.scss

Necessaire pour la refonte du formulaire d'offre.
J'ai repris ce qui etait dans TimeField en l'alégant de beaucoup.
A noté qu'une demande etait en cours via cette preview: https://app.zeplin.io/project/5e05ce53fdf73e9a53ed33e9/screen/5fbf777df7ccbdb52544798d
Les soucies de l'ancien input de durée étant fixé sur celui ci, nous n'en aurons peut etre pas besoin.

TimeInput: add component

---

jest.setup.js
src/components/pages/Signup/Signup.jsx
src/components/pages/Signup/SignupValidation/SignupValidation.jsx
src/components/pages/Signup/SignupValidation/__specs__/SignupValidation.spec.jsx
src/components/pages/Signup/__specs__/Signup.spec.jsx
src/tracking/__mocks__/mediaCampaignsTracking.js
src/tracking/mediaCampaignsTracking.js
src/utils/testHelpers.js

Ticket Jira : https://passculture.atlassian.net/browse/PC-5500
Tests unitaires ajoutés : :+1:

(PC-5500) Ajout des trackers (analytics) pour les campagnes média de Floodlight

---

src/tracking/mediaCampaignsTracking.js
src/tracking/mediaCampaignsTracking.spec.js

Ticket Jira : https://passculture.atlassian.net/browse/PC-5500
Tests unitaires ajoutés : :+1:

(PC-5500) Floodlight tracking : empêcher les doublons d'iframe

---

.env.development
.env.integration
.env.production
.env.staging
.env.testing
config/env.js
config/run_envs/master

Commits à relire séparément.
Attention : **Je n'ai pas reproduit le bug en local ou sur testing.** Je ne sais pas pourquoi : est-ce que la configuration est chargée différemment ?

(PC-5678) config: Add missing DEMARCHES_SIMPLIFIEES_VENUE_RIB_UPLOAD_PROCEDURE_URL

---

src/components/layout/Titles/Titles.jsx
src/components/layout/inputs/Errors/InputError.jsx
src/components/layout/inputs/Select.jsx
src/components/layout/inputs/TextInput/TextInput.jsx
src/components/layout/inputs/TextareaInput.jsx
src/components/pages/Offer/OfferDetails/OfferForm/OfferForm.jsx
src/components/pages/Offer/OfferDetails/OfferForm/SynchronizableProviderInformation.jsx
src/components/pages/Offer/OfferDetails/OfferForm/TypeTreeSelects.jsx
src/components/pages/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx
src/components/pages/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
src/components/pages/Offer/OfferDetails/__specs__/helpers.js
src/components/pages/Styleguide/StyleguideElements/StyleguideTitles.jsx
src/styles/components/layout/Styleguide/_Styleguide.scss
src/styles/components/layout/Titles/_Titles.scss
src/styles/components/layout/inputs/_Select.scss
src/styles/components/pages/Offer/_OfferForm.scss

- test d'édition + fixes
- test de création + fixes
- retour graphique

(PC-5284) : OfferDetails: add tests and implement Jira reviews.

---

src/components/pages/Offer/Stocks/StockItem/StockItem.jsx
src/components/pages/Offer/Stocks/StockItem/StockItem.spec.jsx
src/components/pages/Offer/Stocks/StockItem/StockItemContainer.jsx
src/components/pages/Offer/Stocks/Stocks.jsx
src/components/pages/Offer/Stocks/__specs__/Stocks.spec.jsx
src/styles/components/layout/NotificationV2/_NotificationV2.scss

Edition:
* success: "Les modifications ont été enregistrées.
Si la date de l'évènement a été modifiée, les utilisateurs ayant déjà réservé cette offre seront prévenus par email."
* error: "Impossible de modifier le stock."

(PC-5717) : Add update toaster for stocks

---

src/components/pages/Offer/Stocks/Stocks.jsx
src/components/pages/Offer/Stocks/__specs__/Stocks.spec.jsx

https://passculture.atlassian.net/browse/PC-5733

(PC-5733) : Stock cancelation info wording

---

src/components/layout/inputs/PeriodSelector/PeriodSelector.jsx
src/components/layout/inputs/PeriodSelector/__specs__/PeriodSelector.spec.jsx
src/components/pages/Offers/Offers.jsx
src/components/pages/Offers/__specs__/Offers.spec.jsx
src/styles/components/layout/inputs/PeriodSelector/_PeriodSelector.scss

+ fix a test on offer type filter that was not testing the proper behaviour of the feature.

(PC-5334): Add tests for event period

---

src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
src/components/pages/Offer/Offer/Thumbnail/ImportFromURL/ImportFromURL.jsx
src/components/pages/Offer/Offer/Thumbnail/ThumbnailDialog.jsx
src/components/pages/Offer/Offer/Thumbnail/ThumbnailDialog.scss
src/components/pages/Offer/Offer/Thumbnail/__specs__/Thumbnail.spec.jsx
src/repository/pcapi/__specs__/pcapi.spec.js
src/repository/pcapi/pcapi.js

en draft tant que la PR API n'est pas au moins commencée

(PC-5483): Upload Image - Implementing new route for URL import errors

---

.eslintrc
package.json
quality_assurance/quality_assurance.js

Premier pas en mettant les tests pour que l'autre PR puisse fonctionner puisqu'elle se base sur master.
https://github.com/pass-culture/pass-culture-pro/pull/958

(PC-6130) Implementation of quality assurance tests

---

src/components/layout/inputs/TextareaInput.jsx
src/components/pages/Offer/Offer/OfferDetails/OfferForm/OfferForm.jsx
src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
src/components/pages/Offer/Offer/OfferDetails/__specs__/helpers.js

jira https://passculture.atlassian.net/browse/PC-6295

[PC-6295] OfferForm: name as textare with 90 char limit

---

src/components/pages/Offer/Offer/OfferDetails/OfferForm/OfferEdition.jsx
src/components/pages/Offer/Offer/OfferDetails/OfferForm/OfferForm.jsx
src/components/pages/Offer/Offer/OfferDetails/OfferForm/_constants.js
src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferCreationForPro.spec.jsx
src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
src/components/pages/Offer/Offer/OfferDetails/__specs__/helpers.js

~PR api necessaire à une review en locale: https://github.com/pass-culture/pass-culture-api/pull/1880~ PR backend mergée.
- Ajout de la classe d'erreur et du message d'erreur sur les checkbox à venir dans une PR suivante. ([voir la maquette](https://zpl.io/a8rXojX))

[PC-6293] offers accessibility

---

src/components/pages/Offer/Offer/OfferDetails/OfferForm/OfferForm.jsx

Mauvaise position  !
Ce coup ci c'est la bonne.

[PC-6292] OfferForm, move CGU warning again

---

src/components/layout/LegalInfos/LegalInfos.jsx
src/components/layout/LegalInfos/LegalInfos.scss
src/components/layout/form/fields/PasswordField.jsx
src/components/layout/form/fields/__specs__/PasswordField.spec.jsx
src/components/pages/SetPassword/SetPassword.jsx
src/components/pages/SetPassword/SetPassword.scss
src/components/pages/SetPassword/SetPasswordContainer.js
src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
src/components/pages/Signup/SignupForm/SignupForm.jsx
src/repository/pcapi/pcapi.js
src/store/testUtils.js
src/styles/components/pages/SignupForm/_SignupForm.scss
src/styles/index.scss
src/utils/routes_map.jsx

Zeplin: https://app.zeplin.io/project/5e05ce53fdf73e9a53ed33e9/screen/600807efe260f69af178cb3f
Actual footage:

(PC-6396) Create pro set password screen

---

src/components/pages/Offer/Offer/Stocks/DeleteStockDialog/DeleteStockDialog.jsx
src/components/pages/Offer/Offer/Stocks/StockItem/StockItem.jsx
src/components/pages/Offer/Offer/Stocks/Stocks.jsx
src/components/pages/Offer/Offer/Stocks/__specs__/Stocks.spec.jsx

* add new stocks (unsaved ones)
* delete a existing stock
* the new stocks should not disapear

[PC-6691] Stocks : Fix deleting existing stocks

---

src/components/pages/Home/Offerers.jsx
src/components/pages/Home/__specs__/Homepage.spec.jsx
src/repository/pcapi/pcapi.js

* previously only retrieve validated ones

[PC-6524] Home v2: offerers : retrieve all offerers

---

src/components/pages/Home/Homepage.scss
src/components/pages/Home/Offerers.jsx
src/components/pages/Home/ProfileAndSupport/ProfileAndSupport.jsx
src/components/pages/Home/ProfileAndSupport/__specs__/Profile.spec.jsx
src/components/pages/Home/__specs__/Homepage.spec.jsx

jira https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=31&modal=detail&selectedIssue=PC-6662
deux retours !
* formater le numero de téléphone en XX XX XX XX XX
* ajouter un ellipsis sur l'email.

(PC-6662) home v2 return profile

---

src/components/pages/Home/Offerers.jsx
src/components/pages/Home/__specs__/Homepage.spec.jsx
src/repository/pcapi/pcapi.js

nouvelle PR ici avec le nom qui colle avec le la PR API: https://github.com/pass-culture/pass-culture-api/pull/1971
précédente PR, pour commentaire: https://github.com/pass-culture/pass-culture-pro/pull/1084

[PC-6524] Retrieve unvalidated offerer

---

src/components/pages/Home/Offerers.jsx
src/components/pages/Home/__specs__/Homepage.spec.jsx

Affichage des `venue.publicName` si on en trouve un.

[PC-6671] Home v2 : display venue publicName if any

---

src/components/pages/Home/ProfileAndSupport/Support.jsx
src/components/pages/Home/ProfileAndSupport/Support.scss

J'ai du faire un hack un peu sale pour que l'icone de mail soit à la meme taille que les autres.
En attente d'un svg avec moins de marge afin d'avoir quelquechose de plus clean

[PC-6663] Home v2: Support: fix link design

---

src/components/pages/Home/Homepage.scss
src/components/pages/Home/Offerers.jsx
src/components/pages/Home/ProfileAndSupport/ProfileAndSupport.jsx
src/components/pages/Home/__specs__/Homepage.spec.jsx

[PC-6665] home v2: display account data

---

src/components/pages/Home/Homepage.jsx
src/components/pages/Home/Homepage.scss
src/components/pages/Home/Offerers/Offerers.jsx
src/components/pages/Home/Offerers/OfferersContainer.jsx
src/components/pages/Home/__specs__/Homepage.spec.jsx
src/components/pages/Offerer/OffererDetails/Venues/Venues.jsx
src/styles/global/_page.scss

https://passculture.atlassian.net/browse/PC-6670

[PC-6670] home v2: add create venue banner

---

src/components/pages/Home/Offerers/Offerers.jsx
src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx

https://passculture.atlassian.net/browse/PC-6668

[PC-6668] Home v2: add create offerer option

---

src/components/pages/Home/Homepage.scss
src/components/pages/Home/ProfileAndSupport/Support.scss

Home v2: Some graphic returns

---

src/components/pages/Signup/SignupForm/SignupForm.jsx
src/components/pages/Signup/SignupForm/__specs__/SignupForm.spec.jsx

(PC-4131) PRO - Rendre l'abonnement aux newsletters facultatif lors de l'inscription (IO)

(PC-4131) PRO - Rendre l'abonnement aux newsletters facultatif lors de l'inscription (UX)

---

src/components/pages/Home/Offerers/OffererDetails.jsx
src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx
src/components/pages/Home/Venues/Venue.jsx
src/components/pages/Home/Venues/VenueList.jsx
src/components/pages/Home/Venues/VenueStat.jsx
src/components/pages/Home/Venues/VenueStat.scss
src/components/pages/Home/Venues/__specs__/Venue.spec.jsx
src/styles/index.scss

:heavy_check_mark:  Review graphic 
@TODO:

[PC-6678] home v2: add create offer link

---

src/components/pages/Home/Offerers/OffererDetails.jsx
src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx

* do not consider virtual venues

[PC-6667] home v2: fix no bank data warning

---

src/components/pages/Offers/Offer/Stocks/StockItem/StockItem.jsx
src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx

https://passculture.atlassian.net/browse/PC-6993

[PC-6993] StockItem: fix delete button title wording

---

src/repository/pcapi/pcapi.js

Utilisation des filtre pour les venu ajouter dans la PR back: https://github.com/pass-culture/pass-culture-api/pull/2058

[PC-7136] OfferForm: also retrieve validated for user venues

---

src/components/pages/Offers/Offers/Offers.jsx
src/components/pages/Offers/Offers/__specs__/Offers.spec.jsx

Lien du ticket Jira : https://passculture.atlassian.net/browse/PC-7207
Tests unitaires de non regression ajoutés : 👍🏻

(PC-7207) Fix reset of filters on Offers page

---

src/components/pages/Home/Venues/Venue.jsx
src/components/pages/Home/Venues/Venue.scss
src/styles/index.scss

Autre solution, ellipsis sur le titre ! https://passculture.atlassian.net/browse/PC-7317

[PC-7317] home v2: fix venue long title display

---

src/components/pages/Offerer/OffererDetails/BankInformation/BankInformation.jsx
src/components/pages/Venue/fields/BankInformationFields/BankInformationFields.jsx
src/components/pages/Venue/fields/BankInformationFields/BicIbanFields.jsx
src/components/pages/Venue/fields/BankInformationFields/__specs__/BankInformation.spec.jsx
src/components/pages/Venue/fields/BankInformationFields/__specs__/BicIbanFields.spec.jsx
src/styles/global/_page.scss

https://passculture.atlassian.net/browse/PC-5234

[C-5234] Offerer & Venue: change modify link position

---

src/components/pages/Offers/Offers/OfferItem/OfferItem.jsx
src/components/pages/Offers/Offers/OfferItem/OfferItem.scss
src/components/pages/Offers/Offers/domain/__specs__/computeOfferStatus.spec.js
src/components/pages/Offers/Offers/domain/computeOfferStatus.js
src/components/pages/Offers/Offers/domain/offerStatus.js

(PC-7141): Update status displayed for validated status

---

src/components/pages/Home/Offerers/OffererDetails.jsx
src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx

jira https://passculture.atlassian.net/browse/PC-7236

[PC-7263] Home: Do not display bank info warning if virtual venue have offers

---

src/components/pages/Offers/Offer/Offer.scss
src/components/pages/Offers/Offer/OfferDetails/OfferDetails.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferStatusBanner/OfferStatusBanner.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferStatusBanner/OfferStatusBanner.scss
src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
src/components/pages/Offers/Offer/Stocks/Stocks.jsx
src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
src/styles/index.scss
yarn.lock

La logique avait déjà été faite avant, j'en ai profité pour faire du refacto.
J'ai mis à jour yarn.lock car il y avait un décalage.

(PC-7462) Displaying of status message on stocks page

---

src/components/pages/Offerers/OffererItem/__specs__/OffererItemContainer.spec.jsx
src/components/pages/Offerers/__specs__/OfferersContainer.spec.jsx
src/components/pages/Venue/utils/__specs__/formatPatch.spec.js
src/components/utils/mocks/state.js
src/store/selectors/data/__specs__/mockState.json
src/store/selectors/data/__specs__/offerersSelectors.spec.js

[PC-7809] Venue: remove unused venue.thumbCount attribute

---

src/components/pages/Offers/Offer/Stocks/Stocks.jsx
src/components/pages/Offers/Offer/Stocks/StocksContainer.js
src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
src/components/pages/Offers/Offer/Stocks/_constants.js

(PC-7778) Adaptation de la mention sur la réservation des offres numériques

---

src/components/layout/Banner/Banner.jsx
src/components/layout/Banner/__specs__/Banner.spec.jsx
src/components/pages/Desk/Desk.jsx
src/components/pages/Desk/_Desk.scss
src/components/pages/Desk/__specs__/Desk.spec.jsx
src/components/pages/Home/Offerers/BankInformations.jsx
src/components/pages/Home/Offerers/OffererDetails.jsx
src/components/pages/Offerer/OffererDetails/BankInformation/BankInformation.jsx
src/components/pages/Offerer/OffererDetails/BankInformation/__specs__/BankInformation.spec.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferForm/Messages/OfferRefundWarning.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferForm/Messages/WithdrawalReminder.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferStatusBanner/OfferStatusBanner.jsx
src/components/pages/Reimbursements/__specs__/Reimbursements.spec.jsx
src/components/pages/Styleguide/StyleguideElements/StyleguideBanners.jsx
src/components/pages/Venue/fields/BankInformationFields/ApplicationBanner.jsx
src/components/pages/Venue/fields/BankInformationFields/BankInformationFields.jsx
src/components/pages/Venue/fields/BankInformationFields/__specs__/ApplicationBanner.spec.jsx
src/styles/components/pages/Desk/index.scss
src/styles/components/pages/index.scss
src/styles/index.scss

J'ai mis à jour le composant Banner pour pouvoir injecter des balises dans le message.

(PC-7249) Adding of an informative message

---

src/components/layout/Header/__specs__/HeaderV1.spec.jsx
src/components/layout/Header/_constants.js
src/components/pages/Desk/Desk.jsx
src/components/pages/Desk/__specs__/Desk.spec.jsx
src/components/pages/Home/ProfileAndSupport/Support.jsx
src/components/pages/Home/ProfileAndSupport/__specs__/Support.spec.jsx
src/components/pages/Offerer/OffererDetails/BankInformation/BankInformation.jsx
src/components/pages/Offerer/OffererDetails/BankInformation/__specs__/BankInformation.spec.jsx
src/components/pages/Reimbursements/Reimbursements.jsx
src/components/pages/Reimbursements/__specs__/Reimbursements.spec.jsx
src/components/pages/Signup/SignupForm/SignupForm.jsx
src/components/pages/Signup/SignupForm/__specs__/SignupForm.spec.jsx
src/components/pages/Venue/fields/BankInformationFields/BankInformationFields.jsx
src/components/pages/Venue/fields/BankInformationFields/__specs__/BankInformation.spec.jsx
src/utils/config.js

https://passculture.atlassian.net/browse/PC-8201

(PC-8201) Correction des URLs suite au passage de Crisp à Intercom

---

src/components/pages/Bookings/BookingsRecapTable/Filters/FilterByBookingPeriod.jsx
src/components/pages/Bookings/BookingsRecapTable/Filters/Filters.jsx
src/components/pages/Bookings/BookingsRecapTable/Filters/__specs__/FilterByBookingPeriod.spec.jsx

(FIX) Fix bookings page to disable selection of ending period date after today

---

src/repository/__specs__/venuesService.spec.js
src/repository/pcapi/pcapi.js
src/repository/venuesService.js

backend: pass-culture/pass-culture-api#2333
jira : https://passculture.atlassian.net/browse/PC-7811

[PC-7811] Adapte to new api "/venues" reponse format

---

src/repository/pcapi/pcapi.js

jira: https://passculture.atlassian.net/browse/PC-7817
backend: https://github.com/pass-culture/pass-culture-api/pull/2443

[PC-7817] Api migration list_venue_providers

---

src/components/pages/Bookings/BookingsRecapTable/Header/__specs__/Header.spec.jsx
src/components/pages/Bookings/BookingsRecapTable/utils/__specs__/generateBookingsCsvFile.spec.js
src/components/pages/Bookings/BookingsRecapTable/utils/generateBookingsCsvFile.js

https://passculture.atlassian.net/browse/PC-9407

[PC-9407] Add date used to bookings export csv

---

src/components/pages/Desk/Desk.jsx

Jira: https://passculture.atlassian.net/browse/PC-9221
Review PO: 
KO - Une fois validé, le champ est vide et le focus est dessus pour que je puisse valider une nouvelle contremarque ❌

[PC-9465] Desk: reset token field after submit

---

.env.development
.env.integration
.env.production
.env.staging
.env.testing
config/env.js
config/run_envs/master
src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
src/components/pages/Offerers/Offerer/OffererDetails/Offerer.js
src/components/pages/Offerers/Offerer/OffererDetails/OffererDetails.jsx
src/styles/components/pages/Offerer/ApiKey/_ApiKey.scss
src/styles/components/pages/Offerer/ApiKey/index.scss
src/styles/components/pages/Offerer/index.scss
src/utils/config.js

(PC-8752) Add offerer ApiKey list

---

src/components/layout/CsvTableButton/utils/csvConverter.js

Jira: https://passculture.atlassian.net/browse/PC-9736

[PC-9736] Reimburesment: convert number to local string

---

src/components/pages/Offers/domain/getProviderInfo.js

jira https://passculture.atlassian.net/browse/PC-9695

[PC-9695] Modify CDI-Bookshop provider

---

src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKeyContainer.jsx
src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/__specs__/ApiKey.spec.jsx
src/components/pages/Offerers/Offerer/OffererDetails/Offerer.js
src/components/pages/Offerers/Offerer/OffererDetails/OffererDetails.jsx
src/repository/pcapi/__specs__/pcapi.spec.js
src/repository/pcapi/pcapi.js
src/styles/components/pages/Offerer/ApiKey/_ApiKey.scss
src/styles/mixins/_fonts.scss
src/utils/fakeApi.js

(PC-8753) Add api key generation

---

src/components/layout/CsvTableButton/utils/csvConverter.js

jira: https://passculture.atlassian.net/browse/PC-9736

[PC-9735] Reimbursement: float, replace dot by comma

---

.github/workflows/storybook.yml
package.json

En suivant un tuto plutôt simple [Deploy Storybook to GitHub Pages](https://dev.to/kouts/deploy-storybook-to-github-pages-3bij)  
Essayons d'automatiquement déployer un storybook sur le code de master via la documentation automatique de github. )

[MOB] auto deploy storybook on github docs pages

---

package.json

Par ce que tout le monde n'a pas chrome !

package.json: add cmd to launch testcafe on firefox and chromium

---

src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreation.jsx
src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreationContainer.js
src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/__specs__/VenueCreationContainer.spec.js
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEditionContainer.js
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/__specs__/VenueEditionContainer.spec.js
src/components/pages/Offerers/Offerer/VenueV1/fields/WithdrawalDetailsFields/WithdrawalDetailsFields.jsx
src/components/pages/Offerers/Offerer/VenueV1/utils/formatVenuePayload.js

jira: https://passculture.atlassian.net/browse/PC-8553
backend: https://github.com/pass-culture/pass-culture-api/pull/2768

[PC-8553] Add withdrawalDetails to venue

---

src/components/pages/Home/Offerers/BankInformations.jsx
src/components/pages/Home/Offerers/OffererDetails.jsx
src/components/pages/Home/Offerers/__specs__/OffererDetails.spec.jsx
src/components/pages/Home/Offerers/__specs__/OffererDetailsLegacy.spec.jsx
src/components/pages/Home/Venues/Venue.jsx
src/components/pages/Offerers/Offerer/OffererDetails/BankInformation/BankInformation.jsx
src/components/pages/Offerers/Offerer/OffererDetails/BankInformation/__specs__/BankInformation.spec.jsx
src/components/pages/Offerers/Offerer/OffererDetails/OffererDetails.jsx
src/components/pages/Offerers/Offerer/OffererDetails/__specs__/OffererDetails.spec.jsx

Ticket Jira : https://passculture.atlassian.net/browse/PC-9445

(PC-9445): Replace offerer upload rib by venue upload rib

---

src/components/pages/Offerers/Offerer/VenueV1/fields/WithdrawalDetailsFields/WithdrawalDetailsFields.jsx

jira : https://passculture.atlassian.net/browse/PC-8553

[PC-8553] Offerer.VenueV1: Change wording for withdrawal field

---

src/components/layout/form/fields/CheckboxField.jsx
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx
src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/IdentifierFields.jsx
src/components/pages/Offerers/Offerer/VenueV1/utils/formatVenuePayload.js
src/styles/components/pages/Venue/fields/IdentifierFields/IdentifierFields.scss

jira: https://passculture.atlassian.net/browse/PC-8552
back end: https://github.com/pass-culture/pass-culture-api/pull/2864

[PC-8552] venue: add checkbox to apply email to all offers

---

src/components/pages/Reimbursements/Reimbursements.jsx
src/components/pages/Reimbursements/__specs__/Reimbursements.spec.jsx
src/styles/components/pages/Reimbursements/_Reimbursements.scss

Ajouter plus d'informations dans l'onglet remboursements.

(PC-9453): add explanation in reimbursements page

---

src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProviderItem/VenueProviderItem.jsx
testcafe/06_offers.js

Bug sur la page https://pro.testing.passculture.team/structures/BW6Q/lieux/C52Q?modification
Car providerInfo n'est pas forcément défini.

(PC-10088) Fix venue modification page when provider is not known

---

src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.jsx
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.jsx
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderFormDialog/AllocineProviderFormDialog.jsx
src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderItem/AllocineProviderItem.jsx

Fix code quality errors introduced in #1457

(PC-8558): Fix code quality

---

src/components/pages/Offerers/Offerer/VenueV1/VenueCreation/VenueCreation.jsx
src/components/pages/Offerers/Offerer/VenueV1/fields/BankInformationFields/index.js
src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/IdentifierFields.jsx
src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/__specs__/IdentifierFields.spec.jsx
src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/index.js
src/components/pages/Offerers/Offerer/VenueV1/fields/LocationFields/index.js
src/components/pages/Offerers/Offerer/VenueV1/fields/WithdrawalDetailsFields/index.js
src/components/pages/Offerers/Offerer/VenueV1/utils/formatVenuePayload.js
testcafe/05_venue.js

- ajout d'un champ description à la création / édition d'une venue

(PC-1026): add description field to venues

---

src/components/pages/Offerers/Offerer/VenueV1/fields/AccessibilityFields/AccessibilityFields.jsx

* wording du titre
* ajout d'une asterix 'chanmps obligatoire"
* il n'est plus possible de décocher la dernier case coché (car le champs est obligatoir)

[PC-10266] fix on venue accessibility fields

---

src/components/hooks/useNotification.js
src/components/layout/Notification/Notification.jsx
src/components/pages/Home/ProfileAndSupport/ProfileAndSupport.jsx
src/components/pages/Home/ProfileAndSupport/ProfileAndSupportContainer.jsx
src/components/pages/Home/ProfileAndSupport/ProfileInformationsModal.jsx
src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKey.jsx
src/components/pages/Offerers/Offerer/OffererDetails/ApiKey/ApiKeyContainer.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferDetails.jsx
src/components/pages/Offers/Offer/OfferDetails/OfferDetailsContainer.js

[Jira](https://passculture.atlassian.net/browse/PC-10334)
Ajout de deux hooks à utiliser pour afficher des notification, cela vas :
* nous libérer de la contrainte d'avoir des container sur plusieurs composants
* nous permettre facilement de changer de system de notification par la suite (au besoin), en modifiant le hook.
`const notification = useNotification()`: permet d'afficher une notification lors de l'appel à `notification("mon message")`
`const showMyNotification = useShowNotification('mon message', 'success')`: permet d'afficher une notification prédéfini lors de l'appel à `showMyNotification()`

[BSR] Add hook to handle notifications

---

src/components/pages/Offerers/Offerer/VenueV1/fields/AccessibilityFields/AccessibilityFields.jsx

Venue.AccessibilityFields: wording

---

src/components/pages/Home/ProfileAndSupport/ProfileAndSupport.jsx
src/components/pages/Home/ProfileAndSupport/ProfileAndSupportContainer.jsx
src/components/pages/Home/ProfileAndSupport/ProfileForm/ProfileForm.jsx
src/components/pages/Home/ProfileAndSupport/ProfileForm/index.js
src/components/pages/Home/ProfileAndSupport/ProfileInformationsModal.jsx
src/store/reducers/data.js

to make it easier to poc on formik form, i needed to extract the
ProfileFrom from the ProfileInformationsModal.

[BSR] ProfileForm: split components

---

src/components/pages/Offers/Offer/OfferDetails/OfferThumbnail/OfferThumbnail.scss
src/components/pages/Offers/Offer/Thumbnail/ThumbnailDialog.scss

https://passculture.atlassian.net/browse/PC-11061
Ajouter un arrière-plan blanc pour les prévisualisations d'images à uploader

(PC-11061): upload image preview - add white backgrounds

---

src/components/pages/Offers/Offer/OfferDetails/OfferForm/validators.js

Cette regex vérifie :
- La présence de http:// ou https:// 
- La présence d'a minima un . avec extension d'a minima 2 caractères
Elle autorise : 
- Les lettes de A à Z (majuscule et minuscules)
- Les chiffres de 0 à 9
- Les -, _ et /

(PC-11714): Improve regex for url validation
