src/components/layout/FormPassword.js, src/components/pages/SigninPage.js, src/styles/vendors/bulma-with-overrides.scss
Il reste encore le fait que sur chrome, le background-color des inputs sont jaunes quand on est focus.
Du coup, l'icône oeil ne l'est pas. 
Et sur firefox, cela reste en fond blanc.
=> Fix signin page design

src/components/OffererItem.js, src/components/layout/Header.js
Cette PR permet 
- d'afficher un message annonçant que la structure n'est pas encore activée
- d'afficher les offres seulement si au moins un lieu est ajouté
- d'afficher un message si aucun lieu n'a été ajouté plus un lien
- affiche les offres dans le menu du header même si le user n'a pas ajouté de lieu ou d'offres
@augnustin 
Linked to https://github.com/betagouv/pass-culture-browser/issues/345
=> Fix offerer item informations display

src/components/hocs/withLogin.js, src/components/hocs/withSign.js, src/sagas/user.js
J'avoue c'était ptet pas l'urgence mais ça me tracassait beaucoup : j'aime pas avoir des messages d'erreur dans la console.
Je ne l'ai plus sous la main, mais grosso-modo, lors d'un changement de page, j'avais une erreur qui disait que `setState` avait été appelé sur un composant unmounted et donc qu'on avait des memory leaks.
Mon guess c'était que ça provenait du fait que j'ai ajouté le `withLogin` dans le `PageWrapper` et que `withLogin` lançait une requête dans `componentWillMount`, ce qui n'est pas considéré comme une bonne pratique : https://stackoverflow.com/questions/27139366/why-do-the-react-docs-recommend-doing-ajax-in-componentdidmount-not-componentwi
Je comprends la logique de *il faut lancer la requête le plus tôt possible*, mais a priori ça ne retarde pas beaucoup. 
En …
=> `get /users/me` in `componentDidMount`

scripts/pc.js, src/components/VenueItem.js, testcafe/01_signup.js, testcafe/03_offerers.js, testcafe/05_venue.js
J'ai ajouté quelques petits tricks pour fixer les tests qui passaient pas toujours:
Notamment: 
- ceux qui comptaient sur des ids (comme .eql(structure/AE)). En fait, c'est compliqué d'anticiper l'id qui va etre crée. Même si on part d'une base qui vient juste d'etre vidée par un pc reset-all-db, en fait, le postgres garde quand meme en mémoire les ids des objets precedemment crees puis droppés. Il faudrait carrement faire un rm du postgres_data pour etre sur qu'on cree toujours au test un id AE.
Mais pour etre plus générique, je trouve que c'est en fait mieux d'utiliser la methode .match(/\/structures\/(*[A-Z0-9]$)/ qui permet qu'on se fiche de l'id creee, tant qu'il y en ait au moins un.
Aussi dans le Signup test, je vois encore un fail avec un test sur un logger d'un request Hook ; en …
=> added precision on test cafe

src/components/layout/Main.js, src/components/pages/AccountingPage.js, src/components/pages/CounterPage.js, src/components/pages/HomePage.js, src/components/pages/MediationPage.js, src/components/pages/MediationsPage.js, src/components/pages/OfferPage.js, src/components/pages/OffererPage.js, src/components/pages/OfferersPage.js, src/components/pages/OffersPage.js, src/components/pages/ProfilePage.js, src/components/pages/VenuePage.js
... je merge ca rapidement pour refaire marcher le master qui utilise pass-culture-shared 0.0.20 qui utilise le nouveau login plus simple... Mais pour le moment, c'est plus logique et simple de faire ce hoc withLogin un peu configuré specifiquement pour chaque page plutôt ue de l'imaginer centralement quelque part. (car notamment la SigninPage et la SignuPage ne doivent pas l'avoir)
Une fois qu'on a poussé le mvp of course je suis ouvert à trouver mieux.
=> added withLogin in every pages

package.json, src/components/pages/OfferPage.js
Ah oui parce que jusque là les champs de type Auteur, Performer... dans le form de OfferPAge marchait pas! (car en fait le Form ne savait pas encore gerer les field qui doivent faire du extraData.<clé> = <value>. Maintenant oui.
Pareil je vais merger dans 5 minutes.
=> Make OfferPage Form working with extraData

src/components/pages/OfferersPage.js
de https://github.com/betagouv/pass-culture-browser/issues/529
parce que c'est tellement relou pour les admin de naviguer maintenant sur le pro avec les 1500 offerers telechargés.
Et pour que ca marche, faut que ca ça soit mergé deja: https://github.com/betagouv/pass-culture-api/pull/187
=> #529_added pagination and infinite scroller

src/components/pages/OfferPage.js
Il y a quelque chose d'un peu trop *magique* avec le form, à voir avec @Ledoux peut-être.
En attendant ce fix fait aussi bien le travail, le principe étant d'avoir un champ requis non renseigné pour empêcher la soumission du formulaire.
Issue : https://github.com/betagouv/pass-culture-browser/issues/626
=> #626 Fix bad venueId populated

src/components/pages/VenuePage.js
parce que y a emmaus typiquemnt qui s'est planté en remplissant les coordonnées à la main de sonlieu.
Et c'est vrai que c'est mieux de faire l'ordre Lat puis Long car google maps le donne dans cet ordre.
=> inverted order of long lat fields in venue form

src/components/pages/TermsPage.js, src/utils/config.js
Cela me permettrait de logger la dernière version déployée en prod avec son hash. Ensuite je pourrais la récupérer pour lancer les tests testscafe sur API ticket 916
=> Add git commit hash in termsPage

package.json, src/components/pages/Offer/EventOccurrencesAndStocksManager.jsx, src/components/pages/Offer/index.jsx, src/components/pages/Signup/SignupForm.jsx, testcafe/08_stocks.js, yarn.lock
Explication du problème: le component Modal garde toujours mounté son enfant $modal,même quand on changeait de page. Ainsi si le $modal était avec des eventListeners d'instancés au did mount (specifique à la page où la modal est appelé), ils etaient aussi instancés en side effect sur les autres pages.
Le fix est fait sur shared ici:  https://github.com/betagouv/pass-culture-shared/pull/88
Et de faire ici:
```
yarn install
```
=> [PC 1423] used pcs 101 that unmount modal by default

.circleci/config.yml, package.json
Le but est est de retrouver les screentshots quand il y des erreurs test-café. Ils seront dans circleci dans l'onglet "Artefact" du menu "Test summary"
=> (PC-2130) add test-cafe screenshot to artefact in ci

src/components/pages/Offer/Offer.jsx, src/styles/components/layout/Insert/_Insert.scss
- Ajouter une majuscule à “Utilisation”
- Corriger le texte “à l’exception”
-  L’icône devrait etre cliquable aussi, elle fait parti du bouton
- L’icône devrait etre cliquable aussi, elle fait parti du bouton
=> (PC-2721) fix UI on warning message on digital offer reimbursement

src/styles/components/layout/Insert/_Insert.scss
Juste une mini correction suite à un retour d'Alizée: quand on survole le lien, il ne change pas de couleur
=> (PC-2721) fix a:hover with no change of text color

src/components/pages/Offer/Offer.jsx
Pour expliquer un peu la PR : 
*Bug*
Le message : "Il y a eu un problème sur la création de cette offre : son type est incompatible avec le lieu enregistré" apparaissait sous le champs "type" d'une offre "cinéma vente à distance". Lorsque l'offre était chargé directement (en naviguant directement sur l'url).
Exemple : https://pro.passculture-testing.beta.gouv.fr/offres/HAHQ?lieu=AFEQ&mots-cles=carte%20cinema
*Resolution* 
Il s'avère que des nouvelles fonctionnalités passées (côté front sur le formulaire de creation et côté back sur la base de données) rendent ce cas impossible.
Du coup, on supprime la potentialité d'afficher ce message.
=> (PC-2618): bugfix delete warning message on consistency between venue type and offer type

src/components/pages/Offer/Offer.jsx, src/components/pages/Offer/OfferObject.js, src/components/pages/Offer/StocksManager/StockItem/StockItem.jsx, src/components/pages/Offer/StocksManager/StockItem/StockItemContainer.js, src/components/pages/Offer/StocksManager/StockItem/__specs__/StockItem.spec.jsx, src/components/pages/Offer/StocksManager/StockItem/__specs__/StockItemContainer.spec.jsx, src/components/pages/Offer/StocksManager/StockItem/__specs__/__snapshots__/StockItem.spec.jsx.snap, src/components/pages/Offer/StocksManager/StockItem/sub-components/EditAndDeleteControl/EditAndDeleteControl.jsx, src/components/pages/Offer/StocksManager/StockItem/sub-components/EditAndDeleteControl/__specs__/EditAndDeleteControl.spec.jsx, src/components/pages/Offer/StocksManager/StockItem/sub-components/EditAndDeleteControl/__specs__/__snapshots__/EditAndDeleteControl.spec.jsx.snap, src/components/pages/Offer/StocksManager/StockItem/sub-components/fields/EventFields/__specs__/EventFields.spec.jsx, src/components/pages/Offer/ValueObjects/Offer.js, src/components/pages/Offer/__specs__/Offer.spec.jsx
Cette PR permettra aux pro qui importent les offres depuis Allociné de gérer leurs stocks depuis l'interface PRO. Ils pourront modifier : le nombre de place disponibles, la date limite de réservation et le prix de leur place.
Cette PR va de pair avec : https://github.com/betagouv/pass-culture-api/pull/1019
Story JIRA : https://passculture.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=PC&modal=detail&selectedIssue=PC-2882
=> (PC-2882): Enable stock management for Allocine offers

src/components/pages/Offerers/Offerers.jsx
Pour reproduire le bug, je coupe mon back et je scroll ma page vers le bas et j'avais une boucle infinie d'appel API.
=> (pC-3345): stop the API call when infinite loop

src/components/pages/Offers/OfferItem/OfferItem.jsx, src/components/pages/Offers/Offers.jsx, src/styles/components/pages/Offers/OfferItem/_OfferItem.scss, src/styles/components/pages/Offers/_Offers.scss, testcafe/06_offers.js, testcafe/helpers/navigations.js
Cette PR est associée au ticket 4330 et non 4252.
Le but est de transformer le display actuel des Offers en table plutôt qu'en liste.
=> (PC-4330): Display offer items as a table

config/webpack.config.prod.js
Since dependencies ugrade (patch and minors) the bundle size is bigger
than 2MB. Increase it to 2.5MB.
=> Increase webpack bundle size in production

src/components/pages/Offer/OfferCreation/OfferCreation.jsx
Au niveau de la base de données, il est actuellement possible de créer une offre duo qui n'est pas un événement.
Ici on fait en sorte que ce ne soit pas possible depuis l'interface pro. Sur le formulaire de création d'une offre, il était possible de sélectionner un type "événement", cocher la case "duo" puis changer le type pour un "livre" par exemple, et l'offre créée était quand même considérée comme duo.
=> (PC-4272): fix non duo offer creation

src/components/pages/Offers/Offers.jsx, src/components/pages/Offers/OffersContainer.js, src/components/pages/Offers/__specs__/Offers.spec.jsx
https://passculture.atlassian.net/browse/PC-4815
Cette props n’était pas utilisée dans la section Offers:
```
$ git grep types | grep -v prop-type
Offers.jsx:    const { loadTypes, types, saveSearchFilters } = this.props
Offers.jsx:    types.length === 0 && loadTypes()
OffersContainer.js:    types: state.data.types,
OffersContainer.js:    loadTypes: () => dispatch(requestData({ apiPath: '/types' })),
__specs__/Offers.spec.jsx:      types: [],
```
=> (PC-4815): pages.Offers: remove unused types and loadTypes()

src/components/pages/Offer/MediationsManager/MediationsManager.jsx
Pourquoi découper la phrase en 2 ? Ne peut-on pas écrire simplement ::
{'. Prenez le temps de les choisir avec soin !'}
(Je ne connais pas grand chose à React et JSX, n'hésitez pas à pointer l'évidence...)
=> MediationsManager: Fix typo (missing space between two words)

src/components/pages/Mediation/Mediation.jsx, src/components/pages/Mediation/MediationContainer.js, src/components/pages/Mediation/__specs__/MediationContainer.spec.js, src/components/pages/Offer/OfferCreation/OfferCreation.jsx, src/components/pages/Offer/OfferCreation/OfferCreationContainer.js, src/components/pages/Offer/OfferCreation/__specs__/OfferCreation.spec.jsx, src/components/pages/Offer/OfferEdition/OfferEdition.jsx, src/components/pages/Offer/OfferEdition/OfferEditionContainer.js, src/components/pages/Offer/OfferEdition/__specs__/OfferEdition.spec.jsx, src/repository/pcapi/pcapi.js, src/store/offers/thunks.js
Les page d'edition et de creation d'offre allaient chercher leurs données dans `state.offers.list` et remplissaient `state.data.offers`.
Ici on utilisera `state.offers.list` pour stocker et récupérer les données.
=> (PC-4892): use redux-thunk to retrieve offer

src/components/pages/Offer/OfferCreation/OfferCreation.jsx
j'ai du mal à saisir le fonctionnement global de ce module de formulaire dans shared.
Le fait est qu'apres l'édition state.forms.offer n'est pas à jours, en faisant un reset ici, on force l'utilisation des valeurs initial.
Second commit pour fixer l'activation et la désactivation.
=> (PC-4892): quick fix in order to have a refreshed offer after edition

.eslintrc, src/components/layout/form/fields/TextField.jsx
Link to Notion standard action ticket : https://www.notion.so/D-sactiver-la-r-gle-ESLint-forcant-le-destructuring-des-props-4602256fb4964fc4ba5121948841264b
Note : usage of props WITH destructuring is still enabled.
=> Standard : enable usage of props WITHOUT destructuring

src/components/pages/Offer/OfferCreation/OfferCreation.jsx, src/components/pages/Offer/OfferCreation/__specs__/OfferCreation.spec.jsx, testcafe/06_offers.js
**Problem**: The form was correctly submitted and the new offer was passed as props to OfferCreation as expected.
However, the field 'isDuo' was not controlled. As a result, the checkbox didn't refresh properly.
the property defaultChecked is used on initial render.
If you reloaded the page though, it would show the correct value.
**Fix**: use the property 'checked' which is controlled
**Reference**: https://reactjs.org/docs/forms.html#default-value
=> [PC-5155] Option duo qui se coche automatiquement lors de la création d'offre

src/styles/components/pages/Offers/_ActionsBar.scss
Changement de l'espacement des boutons sur la bar d'actions de la liste des offres:
=> (PC-4888) : Offer action bar design: button spacing

src/styles/components/pages/Offers/_ActionsBar.scss
Les bouton doivent etre centré sur la page et non sur la place restante dans la barre d'action.
=> (PC-4888) : Offers.ActionsBar: center button on page.

src/components/pages/Offer/StocksManager/StockItem/sub-components/DeleteDialog/DeleteDialog.jsx, src/components/pages/Offer/StocksManager/StockItem/sub-components/DeleteDialog/__specs__/DeleteDialog.spec.jsx
Cette modification ajoute des précisions à l'acteur culturel lors de l'annulation d'un stock ou d'une date d'évènement quant à l'annulation des réservations liées.
=> (PC-5019) Edit wording of stock or date cancellation warning

src/components/pages/Offers/Offers.jsx
Les valeurs de status sont traduites, le champs doit etre mappé lors du chargement du composant.
=> (PC-5288) Offers: translate status from browser to api

src/components/pages/Offer/OfferCreation/OfferCreationContainer.js, src/components/pages/Offer/OfferEdition/OfferEditionContainer.js
As we only retrieve the 10 first offerers we cannot display offerer name if the user has more
than 10 offerers.
When we can retrieve it from the venue we use it.
=> (PC-5273) Fix offerer name not being displayed on some offers

src/Root.jsx, src/app/App.jsx, src/app/AppLayout.jsx, src/components/pages/Home/Home.jsx, src/components/pages/Home/__specs__/Home.spec.jsx, src/components/router/FeaturedRoute.jsx, src/store/selectors/data/usersSelectors.js, src/utils/routes_map.jsx
`routes_map` contient maintenant 2 tableaux de routes:
* routeWithMain qui contient les route utilisant le composant `Main`
* routes qui contient les route utilisant le layout de `App`
le layout est configurable (couleur du header, url du bouton back, etc) via le paramétre `layoutConfig` dans la définition de la route.
=> (PC-5428) App: add layout

src/components/pages/Offer/OfferEdition/OfferEdition.jsx, src/components/pages/Offer/OfferEdition/__specs__/OfferEdition.spec.jsx
Since we don't reload the pages using "withLoginRequired" hoc,
history.push on the same route will not be catch by react-router as a
update.
Therefor it'll not execute "componentDidUpdate" and reload the offer.
Here we force offer reoad using loadOffer() submit success
=> OfferEdition : Fix refresh offer on form submit

src/components/layout/form/fields/CheckboxField.jsx, src/components/layout/inputs/CheckboxInput/CheckboxInput.jsx, src/components/pages/Bookings/BookingsRecapTable/Filters/FilterByBookingStatus.jsx, src/components/pages/Bookings/BookingsRecapTable/Filters/__specs__/FilterByBookingStatus.spec.jsx, src/components/pages/Offers/OfferItem/OfferItem.jsx, src/components/pages/Offers/Offers.jsx, src/components/pages/Styleguide/Styleguide.jsx, src/components/pages/Styleguide/StyleguideElements/StyleguideCheckboxes.jsx, src/styles/components/layout/inputs/CheckboxInput/_CheckboxInput.scss
Les style de tout les elements de formulaires sont un peu eclaté, on à :
*  `field-checkbox`, utilisé par final form. (styles/global/form.scss)
* input[type=checkbox], défini par bulma (styles/vendors/_bulma.scss)
J'ai:
* scoper le styles de notre _CheckboxInput.scss, 
* ajouter un composants & sont example dans le styleguide
* ajouter nouvelle classe "input-checkbox" sur le field final-form (composants/layout/form/fields/CheckboxField.js)
=> (PC-5007) : Add checkboxes to style guide

src/service-worker.js
This PR https://github.com/pass-culture/pass-culture-pro/pull/862 unresgistered the service worker.
But for a client with former bundle, its service worker is still in function. And before being unregistered, it tries to load the `service-worker.js` file.
This PR creates an empty service worker so our builder creates and serves it as `/service-worker.js`.
Former bundle won't fail when requesting this file.
=> (PC-5431): Service worker vide

src/components/layout/Thumb.jsx
Le seul endroit où il y a un défilement d'image est sur la page des offres.
Le [lazy loading](https://developer.mozilla.org/fr/docs/Web/HTML/Element/img#attr-loading) permet de télécharger les images uniquement quand on scrolle la page. On gagne un peu de temps au chargement de la page.
=> [quick win] adding of lazy loading on offer images

package.json, src/components/pages/Offer/OfferCreation/OfferCreation.jsx, src/components/pages/Offer/OfferCreation/__specs__/OfferCreationContainer.spec.jsx, src/components/pages/Offer/OfferEdition/__specs__/OfferEditionContainer.spec.jsx, src/components/pages/Offerers/OfferersContainer.jsx, src/components/pages/Offerers/__specs__/OfferersContainer.spec.jsx, src/repository/pcapi/pcapi.js, src/store/selectors/search.js, src/utils/__specs__/query-string.spec.js, src/utils/query-string.js, testcafe/07_stocks.js
`query-string` est devenu absolète depuis que [URLSearchParams](https://developer.mozilla.org/fr/docs/Web/API/URLSearchParams) existe.
[Pourquoi on passe de `null` à '' dans les testcafé ?](https://github.com/sindresorhus/query-string/blob/master/index.js#L250)
=> [quick win] removing of query string

src/components/pages/Bookings/BookingsRecapTable/Table/Body/TableBody.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/Head/TableHead.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/Head/__specs__/Head.spec.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/Paginate/TablePagination.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/Paginate/__specs__/Paginate.spec.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/TableFrame.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/TableWrapper.jsx, src/components/pages/Bookings/BookingsRecapTable/Table/__specs__/TableFrame.spec.jsx, src/components/pages/Bookings/BookingsRecapTable/__specs__/BookingsRecapTable.spec.jsx
actuellement on a des composants qui s'appellent Head, Table, Paginate, Body, ce qui peut générer des warnings car ils se rapprochent de noms de balises standards HTML et en plus sont peu explicites
Ce quick win les renomme juste
=> [Quick Win]: Renaming booking table with less generic names

src/components/layout/form/fields/CheckboxField.jsx, src/components/pages/Bookings/BookingsRecapTable/Filters/FilterByBookingStatus.jsx, src/components/pages/Bookings/BookingsRecapTable/Filters/__specs__/FilterByBookingStatus.spec.jsx, src/components/pages/Offers/OfferItem/OfferItem.jsx, src/components/pages/Offers/Offers.jsx, src/styles/components/layout/inputs/CheckboxInput/_CheckboxInput.scss
This revert changes on components from e781f3145513e10646db7f3fd6d4bbb085cd7cbd
We only keep the "add to styleguide" part
=> (PC-5007) : do not use new CheckboxInput everywhere for now

src/components/pages/Offer/Offer/OfferDetails/OfferDetails.jsx, src/components/pages/Offer/Offer/OfferDetails/OfferForm/OfferForm.jsx, src/components/pages/Offer/Offer/OfferDetails/OfferForm/_constants.js, src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferCreation.spec.jsx, src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx, src/components/pages/Offer/Offer/__specs__/OfferLayout.spec.jsx, src/components/pages/Venue/utils/__specs__/formatPatch.spec.js, src/components/utils/mocks/state.js
form's default values cannot be used as is to assign a api default empty value
Example: checkbox isDuo default form value is "true" and we don't want
it to become "null" if it's unchange.
=====
https://passculture.atlassian.net/browse/PC-5923
=> (PC-5923) : Fix OfferForm api sent values

src/styles/components/layout/NotificationV2/_NotificationV2.scss
Flex est plus fort que width & height, il faut lui indiqué de ne pas s'auto resizer, avec un valeur maximum possible égale à la width demandée.
=> (PC-5717): fix toaster icon size

.circleci/config.yml
Etant donné que nous avons plein de `console.warning` et `console.error` qui sont difficile à enlever et qui ajoutent beaucoup de bruit et donc du temps à la CI, je propose de ne plus les afficher **juste pour la CI**.
On gagne environ 20% de temps.
=> [quick win] adding of silent flag on jest only on ci

src/components/layout/inputs/CheckboxInput/CheckboxInput.jsx, src/styles/components/layout/inputs/CheckboxInput/_CheckboxInput.scss
Erreur du linter css qui check l'ordre alphabétique des css compilé et non de chaque niveau de scss.
J'espère que la ci vas tout de meme passer ...
=> [PC-6411] Fix checkbox position with multiline label

package.json, scripts/compare-screenshots.sh
Lancer `yarn qa:diff` et regardez s'il y a des captures d'écran dans `testcafe_screenshots/diff/`, ce qui suppose qu'il y a des régressions entre master et votre branche.
=> [PC-6130] Quality Assurance

src/components/pages/Offer/Offer/OfferDetails/OfferDetails.jsx, src/components/pages/Offer/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx, src/components/pages/Offer/Offer/OfferLayout.jsx
* Aller sur le détail d’un offre. Exemple https://pro.passculture-testing.beta.gouv.fr/offres/A9PDE/edition
* Modifier la description par exemple. 
* Cliquer sur Enregistrer
* Aller sur les stocks en cloquant en haut sur “Stock et prix” 
* Revenir sur le détail de l’offre en cliquant sur “Détail de l’offre” 
* KO -> Le champ description ne contient pas les dernières informations à jour
=> [PC-6771] OfferForm: fix offer not refresh on form submit

src/components/pages/Home/Homepage.scss
Revue UI : KO
Le bouton “Créer un lieu” doit être de la même taille que “Créer une offre numérique”
=> [PC-6670] Home v2: same width for both actions in create venue box

src/components/pages/Home/Homepage.scss
Revue : KO
les coins des messages jaune et bleu doivent être arrondies
=========================
note: 
La preview à des radius tout petit de 2px, mais apres disuction avec nicolux, on garde les 6px actuel.
=> [PC-6665] home v2, fix bank informations box border

src/components/layout/DownloadButton/__specs__/DownloadButtonContainer.spec.jsx, src/components/layout/Header/__specs__/Header.spec.jsx, src/components/layout/NotificationV2/__specs__/NotificationV2.spec.jsx, src/components/matomo/__specs__/Matomo.spec.jsx, src/components/pages/Bookings/BookingsRecapTable/CellsFormatter/__specs__/BookingStatusCell.spec.jsx, src/components/pages/Desk/__specs__/Desk.spec.jsx, src/components/pages/Venue/VenueCreation/__specs__/VenueCreation.spec.jsx, src/components/pages/Venue/VenueEdition/VenueProvidersManager/StocksProviderForm/__specs__/StocksProviderForm.spec.jsx, src/components/pages/Venue/VenueEdition/__specs__/VenueEdition.spec.jsx, src/store/reducers/notificationReducer.js, src/store/testUtils.js, src/utils/stubStore.js
`getStubStore` n'étant plus utile au profit de `configureTestStore`, il a disparu pour éviter l'effet de la [broken window](https://en.wikipedia.org/wiki/Broken_windows_theory).
=> [quick win] Removing of getStubStore

config/webpackDevServer.config.js
Correction similaire à ce que j'avais fait dans la webapp : pass-culture/pass-culture-browser@2928971fb34ce903c5d752040b51eadb1be8096d
----
Emacs may create lock files whose filename starts with ".#". These
files are picked up by the current webpack dev server config. As soon
as I start to edit a JSX file, the server crashes because it tries to
handle the lock file.
Emacs lock files should be ignored.
This may be fixed eventually upstream with facebook/create-react-app#10706
but in the meantime...
=> webpack: Ignore Emacs lock files on development server

src/components/layout/form/fields/PasswordField.jsx, src/components/layout/form/fields/__specs__/PasswordField.spec.jsx, src/components/pages/SetPassword/__specs__/SetPassword.spec.jsx
Le code partagé directement dans le password/domain entre webapp et pro qui renvoie les messages d'erreurs à afficher côté front cause un gros souci de couplage entre pro et webapp.
C'est très compliqué en l'état de modifier simplement le wording du message d'erreur.
À voir comment on aborde le sujet, peut-être après la suppression de webapp pour éviter du travail inutile mais il faudra enlever ce couplage entre la partie domaine des mots de passes et l'affichage de messages côté front.
=> (PC-7508) Change password error wording

src/components/layout/Tutorial/TutorialDialog.jsx, src/components/layout/Tutorial/__specs__/TutorialDialog.spec.jsx, src/repository/pcapi/__specs__/pcapi.spec.js, src/repository/pcapi/__specs__/pcapiClient.spec.js, src/repository/pcapi/pcapi.js
The old route included the user id, which is not necessary. It makes
the backend code slightly simpler.
---
Pull request correspondante côté backend : pass-culture/pass-culture-api#2444.
=> (PC-8769) Use new /users/tuto-seen route without user id

src/components/pages/Offers/Offer/Stocks/ThingStocks.jsx, src/components/pages/Offers/Offer/Stocks/__specs__/Stocks.spec.jsx
Je n'ai pas pour habitude de tester les classnames, mais comme la non-apparition des bordures rouges sur les champs d'input en erreur a été remonté par le support, je me suis dit que c'était un cas métier à tester. 
Je n'ai pas trouvé meilleur moyen que la classname, mais le nom est suffisament générique pour que ce soit acceptable je trouve.
=> (PC-9225) Fix errors display on thing offers stocks page

src/components/layout/inputs/DurationInput/DurationInput.jsx, src/components/layout/inputs/Errors/InputError.jsx, src/components/layout/inputs/Select.jsx, src/components/layout/inputs/TextInput/TextInput.jsx, src/components/layout/inputs/TextInputWithIcon/TextInputWithIcon.jsx, src/components/layout/inputs/TextareaInput.jsx, src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferForm.jsx, src/components/pages/Offers/Offer/OfferDetails/OfferForm/_constants.js, src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferCreationForPro.spec.jsx, src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx, src/components/pages/Signup/SignupForm/__specs__/SignupForm.spec.jsx
Importer les informations d'un livre depuis un ISBN13 lors de la création d'offre.
Avoir qu'un seul product pour un isbn.
Rendre le champs isbn obligatoire pour la création d'offre de type LIVRE_EDITION.
~~Modification du composant `<InputError/>` pour afficher un lien vers GCU en cas de message d'erreur de non-éligibilité d'un produit.~~
PR [back](https://github.com/pass-culture/pass-culture-api/pull/2595)
-----
Update
Modifier le composant `<InputError/>` pour prendre la prop `children` à la place du `message` pour pouvoir afficher des liens (premier commit)
=> (PC-5091): make isbn field required on offer creation and update InputError to display CGU link

src/components/pages/Offerers/Offerer/Venue/VenueEdition/VenueProvidersManager/VenueProvidersManager.jsx, src/components/pages/Offerers/Offerer/Venue/VenueEdition/VenueProvidersManager/__specs__/VenueProvidersManager.spec.jsx
This field is not used anymore and will be removed from the backend.
As far as I can tell, the `AllocineProviderForm` component does not
use the `venueIdAtOfferProviderIsRequired` property since 430f27e1cf63b90aa6bec4d07a7978fb7da5ce6a.
---
PR liée côté backend : pass-culture/pass-culture-api/pull/2604
=> (PC-9250) offerers: Remove mentions of `Provider.requireProviderIdentifier`

src/components/pages/Offerers/List/Offerers.jsx, src/components/pages/Offerers/Offerer/OffererDetails/OffererDetails.jsx, src/components/pages/Offerers/Offerer/Venue/VenueCreation/VenueCreation.jsx, src/components/pages/Offerers/Offerer/Venue/VenueCreation/__specs__/VenueCreation.spec.jsx, src/components/pages/Offerers/Offerer/Venue/VenueEdition/VenueEdition.jsx, src/components/pages/Offerers/OffererCreation/OffererCreation.jsx, src/components/pages/Offerers/OfferersLayout.jsx, src/styles/components/pages/Offerer/_Offerer.scss, src/styles/components/pages/Venue/_Venue.scss, src/styles/global/_page.scss, src/utils/routes_map.jsx
Pour la nouvelles version de venue, nous avons besoin d'afficher une route enfant dans le layout du container parent.
Pour cela, il nous faut migrer les routes Offerers au nouveaux system de route, là ou AppLayout est directement rendu depuis `src/Root.js`
=> [PC-8599] Move Offerers pages to new route system

src/components/pages/Bookings/__specs__/BookingsRecap.spec.jsx
Actuellement dans un test de [bookingsRecap](https://github.com/pass-culture/pass-culture-pro/blob/7afc0a2696fa3d404718d83f1886674ed7f1042b/src/components/pages/Bookings/__specs__/BookingsRecap.spec.jsx#L319) nous filtrons sur le 8 du mois en cours pour l'eventDate.
Nous faisons ensuite une assertion sur l'argument de la fonction `loadFilteredBookingsRecap` : 
```
expect(getNthCallNthArg(loadFilteredBookingsRecap, 1).eventDate).toStrictEqual(
new Date('2020-06-08T00:00:00.000Z')
)
```
Il semblerait que le système fasse une conversion de la date sélectionnée (le 8/6/2020) en UTC avant de l'envoyer en argument dans la fonction.
```
Error: expect(received).toStrictEqual(expected) // deep equality
Expected: 2020-06-08T00:00:00.000Z
Received: 2020-06-07T22:00:00.000Z
```
Du coup je pense qu'il …
=> (PC-9472): change date format in one test to make it locale and not utc

src/repository/pcapi/__specs__/pcapiClient.spec.js, src/repository/pcapi/pcapiClient.js
Dans le cas où l'api est indisponible, le serveur renvoie une erreur HTTP 503 et une response body sous forme d'une page html.
Fix:
Ne pas parser le body response dans le cas de HTTP status 503.
=> (PC-8826): fix json parse error when service unavailable

src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferCreation.jsx
Il arrive lors du premier chargement que le composant de catégories utilise la variable avant que l'api ai répondu.
Edit: Lors de la création uniquement, le composant OfferCreation n'attend pas le chargement des categories avant de render OfferCategories.
=> [BSR] Initialize offers.categories store entry

src/components/pages/Offers/Offer/OfferDetails/OfferForm/OfferForm.jsx, src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferCreationForPro.spec.jsx, src/components/pages/Offers/Offer/OfferDetails/__specs__/OfferEdition.spec.jsx
juste un `input` utilisé pour le titre d'une offre au lieu d'un `textarea`.
quelques impacts sur les tests dus au fait qu'on ne récupère pas le texte d'un input de la même manière que le texte d'un textarea.
quelques messages es-lint corrigé au sujet d'`await` inutiles. j'en ai ignorés plein d'autres qui nécessitent des refactorings (ce qui dépasse de loin mes compétences front)
=> [PC-10374] prevent user from filling multiline title when creating/editing an offer

src/components/pages/Desk/Desk.jsx, src/components/pages/Desk/__specs__/Desk.spec.jsx
**Objectif:** Désactiver le bouton valider ou invalider sur la page guichet après une validation ou invalidation pour ne pas permettre aux utilisateurs de les spammer.
=> (PC-10353): Reset token after validation or invalidation

src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderFormDialog/AllocineProviderFormDialog.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderFormDialog/AllocineProviderFormDialog.scss, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderItem/AllocineProviderItem.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderItem/__specs__/AllocineProviderItem.spec.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/StocksProviderForm/StocksProviderForm.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProviderItem/VenueProviderItem.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProviderItem/VenueProviderItem.scss, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProviderItem/__specs__/VenueProviderItem.spec.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProvidersManager.jsx, src/repository/pcapi/pcapi.js
**Objectif :** Permettre aux acteurs PRO de modifier les paramètres d'import des offres Allociné (prix, quantité, offres duo)
**Implémentation :** 
- Ajout d'un nouveau composant `AllocineProviderItem` composé de `VenueProviderItem`.
- Ajout d'une modale pour afficher le formulaire d'édition de paramètres.
- Modification du composant `AllocineProviderForm` pour l'utilisation en création ou édition. 
- Tests
=> (PC-8558): Allow allocine provider edition

src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProvidersManager.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProvidersManagerContainer.js
**Objectifs :** Afficher le toaster de succès s’affiche “Les modifications ont bien été importées et s’appliqueront aux nouvelles séances créées.” après l'édition de allociné provider.
=> (PC-8558): display toaster when edited venue provide is saved

.circleci/config.yml
Le premier test café timeout.
```
Failed to load the page at "http://localhost:3001/inscription".
Increase the value of the "pageRequestTimeout" variable, enable the
"retryTestPages" option, or use quarantine mode to perform
additional attempts to execute this test.
You can find troubleshooting information for this issue at
"https://go.devexpress.com/TestCafe_FAQ_ARequestHasFailed.aspx".
```
Il semble que la nouvelle configuration webpack soit tres longue à s'initialiser, on se retrouve avec le server de pro qui n'est pas up lorsque les testcafe commencent.
Il semble que ce fix du 1er test ne soit pas suffisant, suite à ce commit nous nous retrouvons avec deux autres test cassé sur l'erreur suivante:
```
JavaScript error details:
TypeError: Cannot convert undefined or null to object
at …
```
=> [BSR] testcafe: wait for front end server response

src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/AllocineProviderForm.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AllocineProviderForm/__specs__/AllocineProviderForm.spec.jsx
** Objectifs :** Création/Edition Venue provider, Nne pas envoyer une chaîne de caractère vide pour l'attribut `quantity` lorsque l'utilisateur supprime la valeur initiale.
=> (PC-8558): Venue prodvider creation/edition not send quantity when it value is empty

.circleci/config.yml
There has been a service incident on coveralls.io for several days which prevents the rest of the workflow to complete, so we'll catch exceptions during the coverio and coveralls parts of the `unit-tests` job
=> (PC-10982) circleci: don't fail if codecov or coveralls fails

src/components/layout/form/utils/getRequiredValidate.js, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueEdition.jsx, src/components/pages/Offerers/Offerer/VenueV1/fields/AccessibilityFields/AccessibilityFields.jsx, src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/IdentifierFields.jsx, src/components/pages/Offerers/Offerer/VenueV1/fields/IdentifierFields/__specs__/IdentifierFields.spec.jsx, src/ui-kit/CheckboxField/CheckboxField.jsx, testcafe/05_venue.js
* Fix de l'initialisation des champs d'accessibilité à `undefined` afin d'avoir un état "non renseigné (lorsque les valeurs sont `null`, alors elles s'initialisent sur `false`). 
* Ajout de l'argument `required` dans `CheckboxField` afin que cela soit pris en compte sur le enable/disable du bouton de submit
* Initialisation de tout les champs `undefined` à `false` lors de la 1er interaction de l'utilisateur avec l'une des checkboxes.
En bonus dans un commit à part, retrait des `readOnly` inutile sur le composants `IdentifierFields`
=> [PC-10266] venue accessibility add non mandatory mandatory field

src/components/pages/Offerers/Offerer/VenueV1/fields/AccessibilityFields/AccessibilityFields.jsx
=> [PC-10794] apply accessibility to all offer by default

src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/AddVenueProviderButton/AddVenueProviderButton.jsx, src/components/pages/Offerers/Offerer/VenueV1/VenueEdition/VenueProvidersManager/VenueProvidersManager.jsx
During VenueEdition test migration, i've some errors cause of this mandatory props.
I've check with lina, we can display this "import offers" module with a venue that have no siret.
=> VenueEdition.VenueProvidersManager: venue.siret is not mandatory
